---

- name: Update the AMQ Broker on OpenShift Container Platform image stream in OCP cluster
  shell: "oc replace -n {{ imagestreams_templates_namespace }} --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/amq-broker-7-image-streams.yaml"

- name: Update the AMQ Broker on OpenShift Container Platform Scaledown Controller image stream in OCP cluster
  shell: "oc replace -n {{ imagestreams_templates_namespace }} --force -f https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/amq-broker-7-scaledown-controller-image-streams.yaml"

- name: Import AMQ Broker on OpenShift Container Platform image into OCP cluster
  shell: "oc -n {{ imagestreams_templates_namespace }} import-image amq-broker-72-openshift:1.1"

- name: Import AMQ Broker on OpenShift Container Platform Scaledown Controller image into OCP cluster
  shell: "oc -n {{ imagestreams_templates_namespace }} import-image amq-broker-72-scaledown-controller-openshift:1.0"

- name: Update AMQ Broker on OpenShift Container Platform templates in OCP cluster
  shell: |
    for template in amq-broker-72-basic.yaml \
    amq-broker-72-ssl.yaml \
    amq-broker-72-custom.yaml \
    amq-broker-72-persistence.yaml \
    amq-broker-72-persistence-ssl.yaml \
    amq-broker-72-persistence-clustered.yaml \
    amq-broker-72-persistence-clustered-ssl.yaml;
     do
     oc -n {{ imagestreams_templates_namespace }} replace --force -f \
    https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/72-1.1.GA/templates/${template}
     done

- name: Deploy AMQ Broker to Enterprise Services project
  shell: "oc new-app -n {{ enterprise_services_project }} --template={{ amq_broker_template }} -p=AMQ_PROTOCOL={{ amq_broker_protocols }} -p=AMQ_USER={{ amq_broker_user }} -p=AMQ_PASSWORD={{ amq_broker_password }}"

- name: Deploy PostgreSQL database to Enterprise Services project
  shell: "oc new-app -n {{ enterprise_services_project }} -p POSTGRESQL_USER={{ postgresql_user }} -p POSTGRESQL_PASSWORD={{ postgresql_password }} -p POSTGRESQL_DATABASE={{ postgresql_database }} {{ postgresql_template }}"

- name: Deploy PostgreSQL Seed job
  shell: "oc process -f {{ role_path }}/files/postgresql-seed.yaml | oc apply -n {{ enterprise_services_project }} -f-"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
